/**
 * lib/prisma.ts — Prisma ORM v7 singleton for Vercel + any PostgreSQL provider
 * ─────────────────────────────────────────────────────────────────────────────
 * Compatible with ALL standard PostgreSQL providers out of the box.
 *
 * Prisma v7 notes:
 *   - Import path: ../generated/prisma (custom output from prisma-client generator)
 *   - URL / directUrl live in prisma.config.ts, NOT the schema datasource block
 *   - We use @prisma/adapter-pg for the pg driver adapter
 *
 * Connection priority: DATABASE_URL → POSTGRES_URL → POSTGRES_PRISMA_URL
 */

// @ts-ignore -- generated by `prisma generate` before `next build`; not present at lint time
import { PrismaClient } from "../generated/prisma"
import { PrismaPg } from "@prisma/adapter-pg"

// ─── Exported types ───────────────────────────────────────────────────────────

export type PrismaClientType = InstanceType<typeof PrismaClient>

// ─── URL resolution ───────────────────────────────────────────────────────────

function getDatabaseUrl(): string | null {
  return (
    process.env.DATABASE_URL?.trim() ||
    process.env.POSTGRES_URL?.trim() ||
    process.env.POSTGRES_PRISMA_URL?.trim() ||
    null
  )
}

const DATABASE_URL = getDatabaseUrl()
const IS_DATABASE_CONFIGURED = !!DATABASE_URL

// ─── SSL config derived from sslmode in the URL ───────────────────────────────

function buildSslConfig(
  sslmode: string | null
): false | { rejectUnauthorized: boolean } | undefined {
  switch (sslmode) {
    case "disable":
      return false
    case "allow":
    case "prefer":
      return { rejectUnauthorized: false }
    case "require":
      return { rejectUnauthorized: false }
    case "verify-ca":
    case "verify-full":
      return { rejectUnauthorized: true }
    default:
      return { rejectUnauthorized: false }
  }
}

// ─── Build pg PoolConfig from URL ────────────────────────────────────────────

function buildPoolConfig(): Record<string, unknown> {
  if (!DATABASE_URL) {
    throw new Error(
      "[Prisma] No database URL configured. " +
        "Set DATABASE_URL (or POSTGRES_URL / POSTGRES_PRISMA_URL) in your environment."
    )
  }

  let parsed: URL
  try {
    parsed = new URL(DATABASE_URL)
  } catch {
    throw new Error(
      `[Prisma] DATABASE_URL is not a valid URL: "${DATABASE_URL.slice(0, 60)}..."\n` +
        "  Expected format: postgresql://user:password@host:5432/dbname?sslmode=require"
    )
  }

  const sslmode = parsed.searchParams.get("sslmode")
  const ssl = buildSslConfig(sslmode)

  const config: Record<string, unknown> = {
    host: parsed.hostname,
    port: parsed.port ? Number(parsed.port) : 5432,
    user: decodeURIComponent(parsed.username),
    password: decodeURIComponent(parsed.password),
    database: parsed.pathname.replace(/^\//, "") || "postgres",
    max: 1,
    connectionTimeoutMillis: 10_000,
    idleTimeoutMillis: 30_000,
  }

  if (ssl !== undefined) {
    config.ssl = ssl === false ? false : ssl
  }

  return config
}

// ─── Client factory ───────────────────────────────────────────────────────────

function createPrismaClient(): PrismaClientType {
  const poolConfig = buildPoolConfig()

  if (process.env.NODE_ENV === "development") {
    const maskedConfig = {
      ...poolConfig,
      password: poolConfig.password ? "****" : undefined,
    }
    console.log("[Prisma] Creating client with config:", JSON.stringify(maskedConfig))
  }

  return new PrismaClient({
    adapter: new PrismaPg(
      poolConfig as ConstructorParameters<typeof PrismaPg>[0]
    ),
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "error", "warn"]
        : ["error"],
  })
}

// ─── Fallback stub (no DB configured) ────────────────────────────────────────

function createStubClient(): PrismaClientType {
  const reason =
    "No database URL configured. Set DATABASE_URL (or POSTGRES_URL / POSTGRES_PRISMA_URL)."

  return new Proxy({} as PrismaClientType, {
    get(_target, prop) {
      if (prop === "then" || prop === "catch" || prop === "finally") {
        return undefined
      }
      if (typeof prop === "string" && !prop.startsWith("_")) {
        return new Proxy(() => {}, {
          get() {
            throw new Error(`[Prisma] ${reason} Cannot access prisma.${prop}.`)
          },
          apply() {
            throw new Error(`[Prisma] ${reason} Cannot call prisma.${prop}().`)
          },
        })
      }
      return undefined
    },
  })
}

// ─── Singleton ────────────────────────────────────────────────────────────────

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientType | undefined
}

function getPrismaClient(): PrismaClientType {
  if (!IS_DATABASE_CONFIGURED) {
    return createStubClient()
  }
  if (!globalForPrisma.prisma) {
    globalForPrisma.prisma = createPrismaClient()
  }
  return globalForPrisma.prisma
}

export const prisma: PrismaClientType = getPrismaClient()

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma
}

// ─── Public helpers ───────────────────────────────────────────────────────────

/** Returns true when the database URL is set. */
export function isDatabaseConfigured(): boolean {
  return IS_DATABASE_CONFIGURED
}

/**
 * Wraps a database operation and returns null instead of throwing when the
 * database is not configured.
 */
export async function withDatabase<T>(
  operation: () => Promise<T>
): Promise<T | null> {
  if (!IS_DATABASE_CONFIGURED) {
    console.warn(
      "[Prisma] Database operation skipped — no database URL configured."
    )
    return null
  }
  return operation()
}
